<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SURIMI.Common</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

    <PropertyGroup>
        <PackageId>SURIMI.Common</PackageId>
        <Authors>EII</Authors>
        <Description>SURIMI Common utils</Description>
        <Title>The SURIMI Common Utils</Title>
        <PackageProjectUrl>https://github.com/Official-EwE/SURIMI-Common-DotNet</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryUrl>https://github.com/Official-EwE/SURIMI-Common-DotNet</RepositoryUrl>
        <PackageReleaseNotes>Initial version</PackageReleaseNotes>
        <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
        <IncludeSymbols>True</IncludeSymbols>
        <IncludeReferencedProjects>True</IncludeReferencedProjects>
        <Company>EII</Company>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />

        <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="9.6.0" />
        <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="9.3.1" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.12.0" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.12.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.12.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.GrpcNetClient" Version="1.12.0-beta.1" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.12.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.12.0" />

        <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
        <PackageReference Include="Grpc.StatusProto" Version="2.71.0" />
    </ItemGroup>
    
    <ItemGroup>
        <None Include="../README.md" Pack="True" PackagePath="/" />

        <!-- Include targets -->
        <!-- Include your PowerShell script -->
        <None Include="tools/build-push-docker.ps1" Pack="true" PackagePath="tools/" />
    </ItemGroup>
    
    <ItemGroup>
      <None Update="build/SURIMI.Common.targets" Pack="true" PackagePath="" />
    </ItemGroup>

</Project>
